### ISSUE TITLE
Regenerate source-code with new generator template

### ISSUE THREAD

**Issue by PutraSudaryanto** [ommu/mod-member#1]
#### TASK
- [x] setting`setting/admin` `tested`
- [x] profile `setting/profile` `tested`
- [x] profile category `setting/profile-category` `tested`
- [x] document type `setting/document-type` `tested`
- [x] profile document `setting/profile-document` `tested`
- [x] members `manage/admin` `tested`
- [x] userlevel `setting/user-level` `tested`
- [x] member users `manage/user` `tested`
- [x] company type `setting/company-type` `tested`
- [x] member company `manage/company` `tested`
- [x] member contact category `setting/company-type` `tested`
- [x] member company contact `manage/company-contact` `tested`
- [x] member history displayname `history/displayname` `tested`
- [x] member history username `history/username` `tested`
- [ ] member recruiter
- [x] member documents `manage/document` `tested`
- [x] member categories `manage/category` `dropped`
- [x] member views `manage/view` `tested`
- [x] member view history `history/view` `tested`
- [x] friend type `setting/friend-type` `tested`
- [x] friends `manage/friend`
- [x] friend history `history/friend` `tested`
- [x] followers `manage/follower` `tested`
- [x] follower history `history/follower` `tested`
